spring.application.name=jobIT
server.port=${SERVER_PORT:8088}
apiPrefix=/api/v1

###
# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jobit}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
###

###
# JWT Configuration
duy.jwt.base64-secret=${JWT_SECRET}
duy.jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY:86400}
duy.jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_TOKEN_VALIDITY:86400}
###

###
# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
duy.upload-file.base-uri=${UPLOAD_BASE_PATH:./uploads/}
###

###
# Pagination Configuration
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=20
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.sort.sort-parameter=sort
###

###
# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###

