# Development Profile
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable detailed error messages in dev
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.include-exception=true

# Actuator endpoints for development
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
